/**
 * 七大战场关卡配置
 * 结构：campaigns[大关卡] > levels[小关卡] > waveOverrides[波次]
 */

export const campaigns = [
  // ─── 第一章：东门·大胤西宫 ───────────────────────────────────────────────
  {
    id: 1,
    name: "东门·大胤西宫",
    faction: "大胤西宫",
    location: "东门",
    difficultyLabel: "初入江湖",
    difficultyClass: "diff-1",
    description: "龙气禁卫压境，皇朝兵马叩关！",
    levels: [
      {
        id: "1-1",
        name: "先锋探路",
        difficulty: "初入江湖",
        initialGold: 120,
        initialLives: 20,
        waveCount: 4,
        pathNodes: [
          { x: 0, y: 9 }, { x: 7, y: 9 }, { x: 7, y: 4 },
          { x: 16, y: 4 }, { x: 16, y: 13 }, { x: 23, y: 13 },
        ],
        waveOverrides: [
          { enemies: [{ type: "soldier", count: 4 }] },
          { enemies: [{ type: "soldier", count: 4 }, { type: "tank", count: 1 }] },
          { enemies: [{ type: "soldier", count: 5 }, { type: "tank", count: 2 }] },
          { enemies: [{ type: "tank", count: 4 }, { type: "soldier", count: 3 }] },
        ],
      },
      {
        id: "1-2",
        name: "禁卫压境",
        difficulty: "初入江湖",
        initialGold: 110,
        initialLives: 18,
        waveCount: 5,
        pathNodes: [
          { x: 0, y: 9 }, { x: 7, y: 9 }, { x: 7, y: 4 },
          { x: 16, y: 4 }, { x: 16, y: 13 }, { x: 23, y: 13 },
        ],
        waveOverrides: [
          { enemies: [{ type: "soldier", count: 5 }, { type: "tank", count: 1 }] },
          { enemies: [{ type: "tank", count: 3 }, { type: "soldier", count: 4 }] },
          { enemies: [{ type: "tank", count: 4 }, { type: "soldier", count: 3 }] },
          { enemies: [{ type: "tank", count: 5 }, { type: "soldier", count: 4 }] },
          { enemies: [{ type: "tank", count: 6 }, { type: "soldier", count: 5 }, { type: "fast", count: 2 }] },
        ],
      },
      {
        id: "1-3",
        name: "西宫大将",
        difficulty: "小试牛刀",
        initialGold: 100,
        initialLives: 15,
        waveCount: 6,
        pathNodes: [
          { x: 0, y: 9 }, { x: 7, y: 9 }, { x: 7, y: 4 },
          { x: 16, y: 4 }, { x: 16, y: 13 }, { x: 23, y: 13 },
        ],
        waveOverrides: [
          { enemies: [{ type: "soldier", count: 6 }, { type: "tank", count: 2 }] },
          { enemies: [{ type: "tank", count: 4 }, { type: "soldier", count: 5 }] },
          { enemies: [{ type: "tank", count: 5 }, { type: "fast", count: 3 }] },
          { enemies: [{ type: "tank", count: 6 }, { type: "soldier", count: 4 }] },
          { enemies: [{ type: "tank", count: 7 }, { type: "fast", count: 4 }, { type: "soldier", count: 3 }] },
          { enemies: [{ type: "tank", count: 10 }, { type: "soldier", count: 5 }, { type: "fast", count: 3 }] }, // BOSS波
        ],
      },
    ],
  },

  // ─── 第二章：南门·天音寺 ────────────────────────────────────────────────
  {
    id: 2,
    name: "南门·天音寺",
    faction: "天音寺",
    location: "南门",
    difficultyLabel: "初窥门径",
    difficultyClass: "diff-2",
    description: "佛音阵阵，沙弥弟子漫山遍野！",
    levels: [
      {
        id: "2-1",
        name: "沙弥先行",
        difficulty: "初窥门径",
        initialGold: 110,
        initialLives: 18,
        waveCount: 5,
        pathNodes: [
          { x: 0, y: 5 }, { x: 8, y: 5 }, { x: 8, y: 13 },
          { x: 15, y: 13 }, { x: 15, y: 5 }, { x: 23, y: 5 },
        ],
        waveOverrides: [
          { enemies: [{ type: "soldier", count: 8 }] },
          { enemies: [{ type: "soldier", count: 10 }] },
          { enemies: [{ type: "soldier", count: 10 }, { type: "fast", count: 3 }] },
          { enemies: [{ type: "soldier", count: 12 }, { type: "fast", count: 2 }] },
          { enemies: [{ type: "soldier", count: 14 }, { type: "fast", count: 4 }] },
        ],
      },
      {
        id: "2-2",
        name: "金刚护法",
        difficulty: "初窥门径",
        initialGold: 100,
        initialLives: 16,
        waveCount: 6,
        pathNodes: [
          { x: 0, y: 5 }, { x: 8, y: 5 }, { x: 8, y: 13 },
          { x: 15, y: 13 }, { x: 15, y: 5 }, { x: 23, y: 5 },
        ],
        waveOverrides: [
          { enemies: [{ type: "soldier", count: 8 }, { type: "tank", count: 2 }] },
          { enemies: [{ type: "soldier", count: 10 }, { type: "tank", count: 2 }] },
          { enemies: [{ type: "soldier", count: 10 }, { type: "tank", count: 3 }, { type: "fast", count: 3 }] },
          { enemies: [{ type: "soldier", count: 12 }, { type: "tank", count: 3 }] },
          { enemies: [{ type: "soldier", count: 12 }, { type: "tank", count: 4 }, { type: "fast", count: 4 }] },
          { enemies: [{ type: "soldier", count: 15 }, { type: "tank", count: 5 }, { type: "fast", count: 3 }] },
        ],
      },
      {
        id: "2-3",
        name: "天女散花",
        difficulty: "小试牛刀",
        initialGold: 90,
        initialLives: 14,
        waveCount: 7,
        pathNodes: [
          { x: 0, y: 5 }, { x: 8, y: 5 }, { x: 8, y: 13 },
          { x: 15, y: 13 }, { x: 15, y: 5 }, { x: 23, y: 5 },
        ],
        waveOverrides: [
          { enemies: [{ type: "soldier", count: 10 }, { type: "tank", count: 2 }] },
          { enemies: [{ type: "soldier", count: 12 }, { type: "fast", count: 4 }] },
          { enemies: [{ type: "soldier", count: 14 }, { type: "tank", count: 3 }] },
          { enemies: [{ type: "soldier", count: 12 }, { type: "tank", count: 4 }, { type: "fast", count: 4 }] },
          { enemies: [{ type: "soldier", count: 15 }, { type: "tank", count: 3 }, { type: "fast", count: 5 }] },
          { enemies: [{ type: "soldier", count: 16 }, { type: "tank", count: 5 }, { type: "fast", count: 4 }] },
          { enemies: [{ type: "soldier", count: 20 }, { type: "tank", count: 6 }, { type: "fast", count: 6 }] }, // BOSS波
        ],
      },
    ],
  },

  // ─── 第三章：西门·青云剑阁 ──────────────────────────────────────────────
  {
    id: 3,
    name: "西门·青云剑阁",
    faction: "青云剑阁",
    location: "西门",
    difficultyLabel: "剑走偏锋",
    difficultyClass: "diff-3",
    description: "御风剑修御剑而来，快若闪电！",
    levels: [
      {
        id: "3-1",
        name: "御风轻骑",
        difficulty: "剑走偏锋",
        initialGold: 100,
        initialLives: 16,
        waveCount: 5,
        pathNodes: [
          { x: 0, y: 9 }, { x: 4, y: 9 }, { x: 4, y: 3 },
          { x: 10, y: 3 }, { x: 10, y: 14 }, { x: 18, y: 14 },
          { x: 18, y: 6 }, { x: 23, y: 6 },
        ],
        waveOverrides: [
          { enemies: [{ type: "fast", count: 8 }] },
          { enemies: [{ type: "fast", count: 10 }, { type: "soldier", count: 3 }] },
          { enemies: [{ type: "fast", count: 12 }, { type: "soldier", count: 4 }] },
          { enemies: [{ type: "fast", count: 14 }, { type: "soldier", count: 3 }] },
          { enemies: [{ type: "fast", count: 16 }, { type: "soldier", count: 5 }] },
        ],
      },
      {
        id: "3-2",
        name: "剑阵突击",
        difficulty: "剑走偏锋",
        initialGold: 90,
        initialLives: 14,
        waveCount: 6,
        pathNodes: [
          { x: 0, y: 9 }, { x: 4, y: 9 }, { x: 4, y: 3 },
          { x: 10, y: 3 }, { x: 10, y: 14 }, { x: 18, y: 14 },
          { x: 18, y: 6 }, { x: 23, y: 6 },
        ],
        waveOverrides: [
          { enemies: [{ type: "fast", count: 10 }, { type: "soldier", count: 5 }] },
          { enemies: [{ type: "fast", count: 12 }, { type: "soldier", count: 4 }, { type: "tank", count: 1 }] },
          { enemies: [{ type: "fast", count: 14 }, { type: "tank", count: 2 }] },
          { enemies: [{ type: "fast", count: 15 }, { type: "soldier", count: 5 }, { type: "tank", count: 2 }] },
          { enemies: [{ type: "fast", count: 16 }, { type: "tank", count: 3 }] },
          { enemies: [{ type: "fast", count: 18 }, { type: "soldier", count: 6 }, { type: "tank", count: 2 }] },
        ],
      },
      {
        id: "3-3",
        name: "剑阵长老",
        difficulty: "道法自然",
        initialGold: 80,
        initialLives: 12,
        waveCount: 7,
        pathNodes: [
          { x: 0, y: 9 }, { x: 4, y: 9 }, { x: 4, y: 3 },
          { x: 10, y: 3 }, { x: 10, y: 14 }, { x: 18, y: 14 },
          { x: 18, y: 6 }, { x: 23, y: 6 },
        ],
        waveOverrides: [
          { enemies: [{ type: "fast", count: 12 }, { type: "soldier", count: 5 }] },
          { enemies: [{ type: "fast", count: 14 }, { type: "tank", count: 2 }] },
          { enemies: [{ type: "fast", count: 16 }, { type: "soldier", count: 5 }, { type: "tank", count: 2 }] },
          { enemies: [{ type: "fast", count: 18 }, { type: "tank", count: 3 }] },
          { enemies: [{ type: "fast", count: 18 }, { type: "soldier", count: 6 }, { type: "tank", count: 3 }] },
          { enemies: [{ type: "fast", count: 20 }, { type: "tank", count: 4 }] },
          { enemies: [{ type: "fast", count: 22 }, { type: "soldier", count: 8 }, { type: "tank", count: 4 }] }, // BOSS波
        ],
      },
    ],
  },

  // ─── 第四章：北门·三清宗 ────────────────────────────────────────────────
  {
    id: 4,
    name: "北门·三清宗",
    faction: "三清宗",
    location: "北门",
    difficultyLabel: "道法自然",
    difficultyClass: "diff-4",
    description: "五行道兵轮番来袭，天罚难测！",
    levels: [
      {
        id: "4-1",
        name: "五行道兵初试",
        difficulty: "道法自然",
        initialGold: 90,
        initialLives: 15,
        waveCount: 6,
        pathNodes: [
          { x: 0, y: 3 }, { x: 5, y: 3 }, { x: 5, y: 9 },
          { x: 12, y: 9 }, { x: 12, y: 3 }, { x: 18, y: 3 },
          { x: 18, y: 13 }, { x: 23, y: 13 },
        ],
        waveOverrides: [
          { enemies: [{ type: "soldier", count: 6 }, { type: "fast", count: 4 }] },
          { enemies: [{ type: "tank", count: 3 }, { type: "fast", count: 5 }] },
          { enemies: [{ type: "soldier", count: 8 }, { type: "tank", count: 2 }, { type: "fast", count: 4 }] },
          { enemies: [{ type: "fast", count: 8 }, { type: "tank", count: 3 }] },
          { enemies: [{ type: "soldier", count: 8 }, { type: "fast", count: 6 }, { type: "tank", count: 2 }] },
          { enemies: [{ type: "tank", count: 5 }, { type: "fast", count: 8 }, { type: "soldier", count: 6 }] },
        ],
      },
      {
        id: "4-2",
        name: "雷部力士降临",
        difficulty: "道法自然",
        initialGold: 80,
        initialLives: 13,
        waveCount: 7,
        pathNodes: [
          { x: 0, y: 3 }, { x: 5, y: 3 }, { x: 5, y: 9 },
          { x: 12, y: 9 }, { x: 12, y: 3 }, { x: 18, y: 3 },
          { x: 18, y: 13 }, { x: 23, y: 13 },
        ],
        waveOverrides: [
          { enemies: [{ type: "soldier", count: 8 }, { type: "fast", count: 5 }] },
          { enemies: [{ type: "tank", count: 4 }, { type: "fast", count: 6 }] },
          { enemies: [{ type: "soldier", count: 10 }, { type: "tank", count: 3 }, { type: "fast", count: 5 }] },
          { enemies: [{ type: "fast", count: 10 }, { type: "tank", count: 4 }] },
          { enemies: [{ type: "soldier", count: 10 }, { type: "fast", count: 8 }, { type: "tank", count: 3 }] },
          { enemies: [{ type: "tank", count: 6 }, { type: "fast", count: 8 }, { type: "soldier", count: 6 }] },
          { enemies: [{ type: "tank", count: 8 }, { type: "fast", count: 10 }, { type: "soldier", count: 8 }] },
        ],
      },
      {
        id: "4-3",
        name: "三清法相",
        difficulty: "修罗战场",
        initialGold: 70,
        initialLives: 12,
        waveCount: 8,
        pathNodes: [
          { x: 0, y: 3 }, { x: 5, y: 3 }, { x: 5, y: 9 },
          { x: 12, y: 9 }, { x: 12, y: 3 }, { x: 18, y: 3 },
          { x: 18, y: 13 }, { x: 23, y: 13 },
        ],
        waveOverrides: [
          { enemies: [{ type: "soldier", count: 10 }, { type: "fast", count: 6 }] },
          { enemies: [{ type: "tank", count: 5 }, { type: "fast", count: 7 }] },
          { enemies: [{ type: "soldier", count: 10 }, { type: "tank", count: 4 }, { type: "fast", count: 6 }] },
          { enemies: [{ type: "fast", count: 12 }, { type: "tank", count: 5 }] },
          { enemies: [{ type: "soldier", count: 12 }, { type: "fast", count: 8 }, { type: "tank", count: 4 }] },
          { enemies: [{ type: "tank", count: 7 }, { type: "fast", count: 10 }, { type: "soldier", count: 6 }] },
          { enemies: [{ type: "soldier", count: 12 }, { type: "tank", count: 7 }, { type: "fast", count: 10 }] },
          { enemies: [{ type: "tank", count: 10 }, { type: "fast", count: 12 }, { type: "soldier", count: 10 }] }, // BOSS波
        ],
      },
    ],
  },

  // ─── 第五章：空中战场·破军山 ────────────────────────────────────────────
  {
    id: 5,
    name: "空中战场·破军山",
    faction: "破军山",
    location: "空中",
    difficultyLabel: "修罗战场",
    difficultyClass: "diff-5",
    description: "陷阵营死士蜂拥而至，以命换命！",
    levels: [
      {
        id: "5-1",
        name: "死士冲锋",
        difficulty: "修罗战场",
        initialGold: 80,
        initialLives: 14,
        waveCount: 6,
        pathNodes: [
          { x: 0, y: 9 }, { x: 3, y: 9 }, { x: 3, y: 3 },
          { x: 9, y: 3 }, { x: 9, y: 14 }, { x: 15, y: 14 },
          { x: 15, y: 5 }, { x: 20, y: 5 }, { x: 20, y: 12 }, { x: 23, y: 12 },
        ],
        waveOverrides: [
          { enemies: [{ type: "fast", count: 15 }] },
          { enemies: [{ type: "fast", count: 18 }, { type: "soldier", count: 4 }] },
          { enemies: [{ type: "fast", count: 20 }, { type: "soldier", count: 5 }] },
          { enemies: [{ type: "fast", count: 22 }, { type: "soldier", count: 6 }] },
          { enemies: [{ type: "fast", count: 24 }, { type: "soldier", count: 6 }, { type: "tank", count: 2 }] },
          { enemies: [{ type: "fast", count: 26 }, { type: "soldier", count: 8 }, { type: "tank", count: 2 }] },
        ],
      },
      {
        id: "5-2",
        name: "霹雳车轰炸",
        difficulty: "修罗战场",
        initialGold: 70,
        initialLives: 13,
        waveCount: 7,
        pathNodes: [
          { x: 0, y: 9 }, { x: 3, y: 9 }, { x: 3, y: 3 },
          { x: 9, y: 3 }, { x: 9, y: 14 }, { x: 15, y: 14 },
          { x: 15, y: 5 }, { x: 20, y: 5 }, { x: 20, y: 12 }, { x: 23, y: 12 },
        ],
        waveOverrides: [
          { enemies: [{ type: "fast", count: 18 }, { type: "soldier", count: 5 }] },
          { enemies: [{ type: "fast", count: 20 }, { type: "tank", count: 2 }] },
          { enemies: [{ type: "fast", count: 22 }, { type: "soldier", count: 6 }, { type: "tank", count: 2 }] },
          { enemies: [{ type: "fast", count: 24 }, { type: "tank", count: 3 }] },
          { enemies: [{ type: "fast", count: 25 }, { type: "soldier", count: 8 }, { type: "tank", count: 3 }] },
          { enemies: [{ type: "fast", count: 26 }, { type: "tank", count: 4 }] },
          { enemies: [{ type: "fast", count: 28 }, { type: "soldier", count: 8 }, { type: "tank", count: 4 }] },
        ],
      },
      {
        id: "5-3",
        name: "兵形势战将",
        difficulty: "飞升断绝",
        initialGold: 60,
        initialLives: 11,
        waveCount: 9,
        pathNodes: [
          { x: 0, y: 9 }, { x: 3, y: 9 }, { x: 3, y: 3 },
          { x: 9, y: 3 }, { x: 9, y: 14 }, { x: 15, y: 14 },
          { x: 15, y: 5 }, { x: 20, y: 5 }, { x: 20, y: 12 }, { x: 23, y: 12 },
        ],
        waveOverrides: [
          { enemies: [{ type: "fast", count: 20 }, { type: "soldier", count: 6 }] },
          { enemies: [{ type: "fast", count: 22 }, { type: "tank", count: 3 }] },
          { enemies: [{ type: "fast", count: 24 }, { type: "soldier", count: 7 }, { type: "tank", count: 3 }] },
          { enemies: [{ type: "fast", count: 26 }, { type: "tank", count: 4 }] },
          { enemies: [{ type: "fast", count: 26 }, { type: "soldier", count: 8 }, { type: "tank", count: 4 }] },
          { enemies: [{ type: "fast", count: 28 }, { type: "tank", count: 5 }] },
          { enemies: [{ type: "fast", count: 28 }, { type: "soldier", count: 10 }, { type: "tank", count: 4 }] },
          { enemies: [{ type: "fast", count: 30 }, { type: "tank", count: 5 }, { type: "soldier", count: 8 }] },
          { enemies: [{ type: "fast", count: 35 }, { type: "tank", count: 7 }, { type: "soldier", count: 10 }] }, // BOSS波
        ],
      },
    ],
  },

  // ─── 第六章：地底·天涯书院 ──────────────────────────────────────────────
  {
    id: 6,
    name: "地底·天涯书院",
    faction: "天涯书院",
    location: "地底",
    difficultyLabel: "飞升断绝",
    difficultyClass: "diff-6",
    description: "大儒虚影引领精英修士，步步为营！",
    levels: [
      {
        id: "6-1",
        name: "行路学子渗透",
        difficulty: "飞升断绝",
        initialGold: 70,
        initialLives: 12,
        waveCount: 7,
        pathNodes: [
          { x: 0, y: 6 }, { x: 4, y: 6 }, { x: 4, y: 14 },
          { x: 10, y: 14 }, { x: 10, y: 3 }, { x: 16, y: 3 },
          { x: 16, y: 11 }, { x: 21, y: 11 }, { x: 21, y: 6 }, { x: 23, y: 6 },
        ],
        waveOverrides: [
          { enemies: [{ type: "soldier", count: 8 }, { type: "fast", count: 6 }] },
          { enemies: [{ type: "tank", count: 4 }, { type: "fast", count: 6 }] },
          { enemies: [{ type: "soldier", count: 10 }, { type: "tank", count: 4 }, { type: "fast", count: 5 }] },
          { enemies: [{ type: "fast", count: 10 }, { type: "tank", count: 5 }] },
          { enemies: [{ type: "soldier", count: 10 }, { type: "fast", count: 8 }, { type: "tank", count: 4 }] },
          { enemies: [{ type: "tank", count: 6 }, { type: "fast", count: 10 }, { type: "soldier", count: 6 }] },
          { enemies: [{ type: "tank", count: 8 }, { type: "fast", count: 10 }, { type: "soldier", count: 8 }] },
        ],
      },
      {
        id: "6-2",
        name: "史官引路",
        difficulty: "飞升断绝",
        initialGold: 60,
        initialLives: 11,
        waveCount: 8,
        pathNodes: [
          { x: 0, y: 6 }, { x: 4, y: 6 }, { x: 4, y: 14 },
          { x: 10, y: 14 }, { x: 10, y: 3 }, { x: 16, y: 3 },
          { x: 16, y: 11 }, { x: 21, y: 11 }, { x: 21, y: 6 }, { x: 23, y: 6 },
        ],
        waveOverrides: [
          { enemies: [{ type: "soldier", count: 10 }, { type: "fast", count: 7 }] },
          { enemies: [{ type: "tank", count: 5 }, { type: "fast", count: 8 }] },
          { enemies: [{ type: "soldier", count: 10 }, { type: "tank", count: 5 }, { type: "fast", count: 7 }] },
          { enemies: [{ type: "fast", count: 12 }, { type: "tank", count: 6 }] },
          { enemies: [{ type: "soldier", count: 12 }, { type: "fast", count: 10 }, { type: "tank", count: 5 }] },
          { enemies: [{ type: "tank", count: 7 }, { type: "fast", count: 12 }, { type: "soldier", count: 8 }] },
          { enemies: [{ type: "soldier", count: 12 }, { type: "tank", count: 8 }, { type: "fast", count: 10 }] },
          { enemies: [{ type: "tank", count: 10 }, { type: "fast", count: 12 }, { type: "soldier", count: 10 }] },
        ],
      },
      {
        id: "6-3",
        name: "大儒虚影",
        difficulty: "飞升断绝",
        initialGold: 50,
        initialLives: 10,
        waveCount: 9,
        pathNodes: [
          { x: 0, y: 6 }, { x: 4, y: 6 }, { x: 4, y: 14 },
          { x: 10, y: 14 }, { x: 10, y: 3 }, { x: 16, y: 3 },
          { x: 16, y: 11 }, { x: 21, y: 11 }, { x: 21, y: 6 }, { x: 23, y: 6 },
        ],
        waveOverrides: [
          { enemies: [{ type: "soldier", count: 10 }, { type: "fast", count: 8 }, { type: "tank", count: 3 }] },
          { enemies: [{ type: "tank", count: 6 }, { type: "fast", count: 10 }] },
          { enemies: [{ type: "soldier", count: 12 }, { type: "tank", count: 6 }, { type: "fast", count: 8 }] },
          { enemies: [{ type: "fast", count: 14 }, { type: "tank", count: 7 }] },
          { enemies: [{ type: "soldier", count: 12 }, { type: "fast", count: 12 }, { type: "tank", count: 6 }] },
          { enemies: [{ type: "tank", count: 9 }, { type: "fast", count: 12 }, { type: "soldier", count: 8 }] },
          { enemies: [{ type: "soldier", count: 14 }, { type: "tank", count: 9 }, { type: "fast", count: 12 }] },
          { enemies: [{ type: "tank", count: 11 }, { type: "fast", count: 14 }, { type: "soldier", count: 10 }] },
          { enemies: [{ type: "tank", count: 13 }, { type: "fast", count: 16 }, { type: "soldier", count: 12 }] }, // BOSS波
        ],
      },
      {
        id: "6-4",
        name: "精英联军加码",
        difficulty: "万劫不复",
        initialGold: 50,
        initialLives: 9,
        waveCount: 10,
        pathNodes: [
          { x: 0, y: 6 }, { x: 4, y: 6 }, { x: 4, y: 14 },
          { x: 10, y: 14 }, { x: 10, y: 3 }, { x: 16, y: 3 },
          { x: 16, y: 11 }, { x: 21, y: 11 }, { x: 21, y: 6 }, { x: 23, y: 6 },
        ],
        waveOverrides: [
          { enemies: [{ type: "soldier", count: 12 }, { type: "fast", count: 10 }, { type: "tank", count: 4 }] },
          { enemies: [{ type: "tank", count: 7 }, { type: "fast", count: 12 }] },
          { enemies: [{ type: "soldier", count: 14 }, { type: "tank", count: 7 }, { type: "fast", count: 10 }] },
          { enemies: [{ type: "fast", count: 16 }, { type: "tank", count: 8 }] },
          { enemies: [{ type: "soldier", count: 14 }, { type: "fast", count: 14 }, { type: "tank", count: 7 }] },
          { enemies: [{ type: "tank", count: 10 }, { type: "fast", count: 14 }, { type: "soldier", count: 10 }] },
          { enemies: [{ type: "soldier", count: 16 }, { type: "tank", count: 10 }, { type: "fast", count: 14 }] },
          { enemies: [{ type: "tank", count: 12 }, { type: "fast", count: 16 }, { type: "soldier", count: 12 }] },
          { enemies: [{ type: "soldier", count: 16 }, { type: "tank", count: 12 }, { type: "fast", count: 16 }] },
          { enemies: [{ type: "tank", count: 15 }, { type: "fast", count: 18 }, { type: "soldier", count: 14 }] },
        ],
      },
    ],
  },

  // ─── 第七章：最终决战·万劫魔宫 ─────────────────────────────────────────
  {
    id: 7,
    name: "最终决战·万劫魔宫",
    faction: "六宗围攻",
    location: "万劫魔宫",
    difficultyLabel: "万劫不复",
    difficultyClass: "diff-7",
    description: "六大宗门合力围攻，此战决定魔道存亡！",
    levels: [
      {
        id: "7-1",
        name: "六宗前锋合流",
        difficulty: "万劫不复",
        initialGold: 150,
        initialLives: 10,
        waveCount: 8,
        pathNodes: [
          { x: 0, y: 9 }, { x: 3, y: 9 }, { x: 3, y: 2 },
          { x: 8, y: 2 }, { x: 8, y: 15 }, { x: 14, y: 15 },
          { x: 14, y: 5 }, { x: 19, y: 5 }, { x: 19, y: 13 },
          { x: 23, y: 13 },
        ],
        waveOverrides: [
          { enemies: [{ type: "soldier", count: 10 }, { type: "fast", count: 8 }, { type: "tank", count: 4 }] },
          { enemies: [{ type: "fast", count: 15 }, { type: "tank", count: 5 }] },
          { enemies: [{ type: "soldier", count: 12 }, { type: "fast", count: 12 }, { type: "tank", count: 5 }] },
          { enemies: [{ type: "tank", count: 8 }, { type: "fast", count: 14 }] },
          { enemies: [{ type: "soldier", count: 14 }, { type: "fast", count: 14 }, { type: "tank", count: 6 }] },
          { enemies: [{ type: "tank", count: 10 }, { type: "fast", count: 16 }, { type: "soldier", count: 10 }] },
          { enemies: [{ type: "soldier", count: 16 }, { type: "tank", count: 10 }, { type: "fast", count: 16 }] },
          { enemies: [{ type: "tank", count: 12 }, { type: "fast", count: 18 }, { type: "soldier", count: 14 }] },
        ],
      },
      {
        id: "7-2",
        name: "宗门精锐齐出",
        difficulty: "万劫不复",
        initialGold: 130,
        initialLives: 10,
        waveCount: 10,
        pathNodes: [
          { x: 0, y: 9 }, { x: 3, y: 9 }, { x: 3, y: 2 },
          { x: 8, y: 2 }, { x: 8, y: 15 }, { x: 14, y: 15 },
          { x: 14, y: 5 }, { x: 19, y: 5 }, { x: 19, y: 13 },
          { x: 23, y: 13 },
        ],
        waveOverrides: [
          { enemies: [{ type: "soldier", count: 12 }, { type: "fast", count: 12 }, { type: "tank", count: 5 }] },
          { enemies: [{ type: "fast", count: 18 }, { type: "tank", count: 6 }] },
          { enemies: [{ type: "soldier", count: 14 }, { type: "fast", count: 14 }, { type: "tank", count: 6 }] },
          { enemies: [{ type: "tank", count: 9 }, { type: "fast", count: 18 }] },
          { enemies: [{ type: "soldier", count: 16 }, { type: "fast", count: 16 }, { type: "tank", count: 7 }] },
          { enemies: [{ type: "tank", count: 11 }, { type: "fast", count: 18 }, { type: "soldier", count: 12 }] },
          { enemies: [{ type: "soldier", count: 16 }, { type: "tank", count: 11 }, { type: "fast", count: 18 }] },
          { enemies: [{ type: "tank", count: 13 }, { type: "fast", count: 20 }, { type: "soldier", count: 14 }] },
          { enemies: [{ type: "soldier", count: 18 }, { type: "tank", count: 13 }, { type: "fast", count: 20 }] },
          { enemies: [{ type: "tank", count: 15 }, { type: "fast", count: 22 }, { type: "soldier", count: 16 }] },
        ],
      },
      {
        id: "7-3",
        name: "六大长老现身",
        difficulty: "万劫不复",
        initialGold: 120,
        initialLives: 10,
        waveCount: 11,
        pathNodes: [
          { x: 0, y: 9 }, { x: 3, y: 9 }, { x: 3, y: 2 },
          { x: 8, y: 2 }, { x: 8, y: 15 }, { x: 14, y: 15 },
          { x: 14, y: 5 }, { x: 19, y: 5 }, { x: 19, y: 13 },
          { x: 23, y: 13 },
        ],
        waveOverrides: [
          { enemies: [{ type: "soldier", count: 14 }, { type: "fast", count: 14 }, { type: "tank", count: 6 }] },
          { enemies: [{ type: "fast", count: 20 }, { type: "tank", count: 7 }] },
          { enemies: [{ type: "soldier", count: 16 }, { type: "fast", count: 16 }, { type: "tank", count: 7 }] },
          { enemies: [{ type: "tank", count: 10 }, { type: "fast", count: 20 }] },
          { enemies: [{ type: "soldier", count: 18 }, { type: "fast", count: 18 }, { type: "tank", count: 8 }] },
          { enemies: [{ type: "tank", count: 12 }, { type: "fast", count: 20 }, { type: "soldier", count: 14 }] },
          { enemies: [{ type: "soldier", count: 18 }, { type: "tank", count: 12 }, { type: "fast", count: 20 }] },
          { enemies: [{ type: "tank", count: 14 }, { type: "fast", count: 22 }, { type: "soldier", count: 16 }] },
          { enemies: [{ type: "soldier", count: 20 }, { type: "tank", count: 14 }, { type: "fast", count: 22 }] },
          { enemies: [{ type: "tank", count: 16 }, { type: "fast", count: 24 }, { type: "soldier", count: 18 }] },
          { enemies: [{ type: "tank", count: 18 }, { type: "fast", count: 26 }, { type: "soldier", count: 20 }] },
        ],
      },
      {
        id: "7-4",
        name: "天道降临",
        difficulty: "万劫不复",
        initialGold: 120,
        initialLives: 10,
        waveCount: 12,
        pathNodes: [
          { x: 0, y: 9 }, { x: 3, y: 9 }, { x: 3, y: 2 },
          { x: 8, y: 2 }, { x: 8, y: 15 }, { x: 14, y: 15 },
          { x: 14, y: 5 }, { x: 19, y: 5 }, { x: 19, y: 13 },
          { x: 23, y: 13 },
        ],
        isFinalLevel: true,  // 通关后触发特殊结算
        waveOverrides: [
          { enemies: [{ type: "soldier", count: 16 }, { type: "fast", count: 16 }, { type: "tank", count: 8 }] },
          { enemies: [{ type: "fast", count: 24 }, { type: "tank", count: 9 }] },
          { enemies: [{ type: "soldier", count: 18 }, { type: "fast", count: 20 }, { type: "tank", count: 9 }] },
          { enemies: [{ type: "tank", count: 12 }, { type: "fast", count: 24 }] },
          { enemies: [{ type: "soldier", count: 20 }, { type: "fast", count: 22 }, { type: "tank", count: 10 }] },
          { enemies: [{ type: "tank", count: 14 }, { type: "fast", count: 24 }, { type: "soldier", count: 16 }] },
          { enemies: [{ type: "soldier", count: 22 }, { type: "tank", count: 14 }, { type: "fast", count: 24 }] },
          { enemies: [{ type: "tank", count: 16 }, { type: "fast", count: 26 }, { type: "soldier", count: 18 }] },
          { enemies: [{ type: "soldier", count: 24 }, { type: "tank", count: 16 }, { type: "fast", count: 26 }] },
          { enemies: [{ type: "tank", count: 18 }, { type: "fast", count: 28 }, { type: "soldier", count: 20 }] },
          { enemies: [{ type: "soldier", count: 24 }, { type: "tank", count: 20 }, { type: "fast", count: 28 }] },
          { enemies: [{ type: "tank", count: 24 }, { type: "fast", count: 32 }, { type: "soldier", count: 26 }] }, // 终极BOSS波
        ],
      },
    ],
  },
];
